### ISSUE TITLE
Rename Repository/Package

### ISSUE THREAD

**Issue by socieboy** [laravel/jetstream-js#5]
I recently migrate from Laravel 7 to 8, and I started using Inertia in one of my apps, and I found the Jetstream package for L8 was using this repository to work with Inertia and forms.

This is just a suggestion to rename the repo to something like laravel-inertia-forms, because i'm using the repo without Jetstream and i think many other developers can use this repo and take advantage of the beautiful features you have done to track errors and handle form request and upload files with JS.

It just an idea and probably you can get more support on this repo when is more explicit about what actually does.

Thank you for the great job!

**Comment by driesvints** [comment]
Heya. Thanks for the kind words. We're going to leave it as is because renaming would mean an unnecessary breaking change for everyone who is already using Jetstream. People can still use this package separately if they want with the current name. Although I'd advice against that as we don't consider the JS used in this package as public API so it can be changed at any time as we see fit.
